"""empty message

Revision ID: 984833548e72
Revises:
Create Date: 2024-06-25 02:24:34.566784

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

import app
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '984833548e72'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('created_at', app.types.unixepoch.Unixepoch(), nullable=False),
                    sa.Column('updated_at', app.types.unixepoch.Unixepoch(), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
